//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boutique.Resources;

using System;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Strings
{
    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Strings()
    {
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Boutique.Resources.Strings", typeof(Strings).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture);
    public static string Tab_Distribution => ResourceManager.GetString("Tab_Distribution", resourceCulture);
    public static string Tab_OutfitCreator => ResourceManager.GetString("Tab_OutfitCreator", resourceCulture);
    public static string Tab_ArmorPatch => ResourceManager.GetString("Tab_ArmorPatch", resourceCulture);
    public static string Tab_Settings => ResourceManager.GetString("Tab_Settings", resourceCulture);
    public static string Settings_Title => ResourceManager.GetString("Settings_Title", resourceCulture);
    public static string Settings_SkyrimRelease => ResourceManager.GetString("Settings_SkyrimRelease", resourceCulture);
    public static string Settings_SkyrimDataPath => ResourceManager.GetString("Settings_SkyrimDataPath", resourceCulture);
    public static string Settings_PatchFileName => ResourceManager.GetString("Settings_PatchFileName", resourceCulture);
    public static string Settings_OutputPath => ResourceManager.GetString("Settings_OutputPath", resourceCulture);
    public static string Settings_OutputPathTooltip => ResourceManager.GetString("Settings_OutputPathTooltip", resourceCulture);
    public static string Settings_Detection => ResourceManager.GetString("Settings_Detection", resourceCulture);
    public static string Settings_Theme => ResourceManager.GetString("Settings_Theme", resourceCulture);
    public static string Settings_Language => ResourceManager.GetString("Settings_Language", resourceCulture);
    public static string Settings_Tutorial => ResourceManager.GetString("Settings_Tutorial", resourceCulture);
    public static string Button_Browse => ResourceManager.GetString("Button_Browse", resourceCulture);
    public static string Button_AutoDetect => ResourceManager.GetString("Button_AutoDetect", resourceCulture);
    public static string Button_RestartTutorial => ResourceManager.GetString("Button_RestartTutorial", resourceCulture);
    public static string Button_Refresh => ResourceManager.GetString("Button_Refresh", resourceCulture);
    public static string Status_Patch => ResourceManager.GetString("Status_Patch", resourceCulture);
    public static string Status_Ready => ResourceManager.GetString("Status_Ready", resourceCulture);
    public static string Status_Loading => ResourceManager.GetString("Status_Loading", resourceCulture);
    public static string Status_Initializing => ResourceManager.GetString("Status_Initializing", resourceCulture);
    public static string Theme_System => ResourceManager.GetString("Theme_System", resourceCulture);
    public static string Theme_Light => ResourceManager.GetString("Theme_Light", resourceCulture);
    public static string Theme_Dark => ResourceManager.GetString("Theme_Dark", resourceCulture);
    public static string Detection_MO2DataPath => ResourceManager.GetString("Detection_MO2DataPath", resourceCulture);
    public static string Detection_MO2GamePath => ResourceManager.GetString("Detection_MO2GamePath", resourceCulture);
    public static string Detection_MO2VirtualStore => ResourceManager.GetString("Detection_MO2VirtualStore", resourceCulture);
    public static string Detection_MO2USVFS => ResourceManager.GetString("Detection_MO2USVFS", resourceCulture);
    public static string Detection_Mutagen => ResourceManager.GetString("Detection_Mutagen", resourceCulture);
    public static string Detection_Failed => ResourceManager.GetString("Detection_Failed", resourceCulture);
    public static string SkyrimRelease_SE => ResourceManager.GetString("SkyrimRelease_SE", resourceCulture);
    public static string SkyrimRelease_VR => ResourceManager.GetString("SkyrimRelease_VR", resourceCulture);
    public static string SkyrimRelease_GOG => ResourceManager.GetString("SkyrimRelease_GOG", resourceCulture);
    public static string Dialog_SelectDataFolder => ResourceManager.GetString("Dialog_SelectDataFolder", resourceCulture);
    public static string Dialog_SelectOutputFolder => ResourceManager.GetString("Dialog_SelectOutputFolder", resourceCulture);
}
